spring.application.name=beatyBook
spring.datasource.url=jdbc:mysql://localhost:3306/beautybook_db
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=to-jest-moj-bardzo-dlugi-sekretny-klucz-do-jwt-pracownia-urody-hola-2026
jwt.expiration=3600000
